# Generated by Django 5.1.6 on 2025-08-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('waste_type', models.CharField(choices=[('organic', 'Organic'), ('recyclable', 'Recyclable'), ('hazardous', 'Hazardous'), ('mixed', 'Mixed')], max_length=20)),
                ('special_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
