"""
Django settings for ecotrack project.
Generated by 'django-admin startproject' using Django 5.1.6.
For more info: https://docs.djangoproject.com/en/5.1/
"""

from pathlib import Path
import os

# -----------------------------
# Project base directory
# -----------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# -----------------------------
# Security settings
# -----------------------------
SECRET_KEY = 'django-insecure-nujn7d*=nyt+t5b3&*&jv#n3piivv0-_m20v701=k^&@^^og3a'
DEBUG = True
ALLOWED_HOSTS = []

# Use our custom user model
AUTH_USER_MODEL = 'accounts.CustomUser'

# -----------------------------
# Installed apps
# -----------------------------
INSTALLED_APPS = [
    # Default Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Custom apps
    'accounts',         # Handles login/signup and user roles
    'core',             # Public pages like home, contact, about
    'ecotracksys',      # Main system: pickups, zones, dashboards
]

# -----------------------------
# Middleware
# -----------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecotrack.urls'

# -----------------------------
# Templates
# -----------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Look for templates in the ecotracksys/templates directory
        'DIRS': [os.path.join(BASE_DIR, 'ecotracksys', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # required for auth
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecotrack.wsgi.application'

# -----------------------------
# Database
# -----------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# -----------------------------
# Password validation
# -----------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# -----------------------------
# Localization
# -----------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# -----------------------------
# Static files (CSS, JS, images)
# -----------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # Project-level static files

# -----------------------------
# Media files (user uploads)
# -----------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# -----------------------------
# Messages framework storage
# -----------------------------
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# -----------------------------
# Authentication
# -----------------------------
LOGIN_URL = '/accounts/login/'           # Redirect if login_required fails
LOGIN_REDIRECT_URL = '/citizen/dashboard/'  # After login
LOGOUT_REDIRECT_URL = '/accounts/login/'   # After logout
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # default
    'accounts.backends.EmailBackend',             # custom email backend
]

# -----------------------------
# Email backend for development
# -----------------------------
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # prints emails to console
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'youremail@gmail.com'
EMAIL_HOST_PASSWORD = 'your-app-password'
DEFAULT_FROM_EMAIL = 'noreply@ecotrack.com'

# -----------------------------
# Default primary key type
# -----------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
