# Generated by Django 5.1.6 on 2025-08-24 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('ecotracksys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='ecotracksys.zone'),
        ),
    ]
