# Generated by Django 5.1.6 on 2025-09-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shift_active',
            field=models.BooleanField(default=False),
        ),
    ]
