# Generated by Django 5.1.6 on 2025-08-12 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_user_id_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
