# Generated by Django 5.1.6 on 2025-08-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotracksys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuprequest',
            name='waste_type',
            field=models.CharField(choices=[('biodegradable', 'Biodegradable / Organic Waste'), ('recyclable', 'Recyclable Waste'), ('residual', 'Non-Recyclable / Residual Waste'), ('ewaste', 'E-Waste'), ('hazardous', 'Hazardous Waste'), ('construction', 'Construction & Demolition Waste')], max_length=50),
        ),
    ]
