# Generated by Django 5.1.6 on 2025-08-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotracksys', '0002_alter_pickuprequest_waste_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickuprequest',
            options={},
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='waste_type',
            field=models.CharField(choices=[('organic', 'Biodegradable / Organic Waste'), ('recyclable', 'Recyclable Waste'), ('nonrecyclable', 'Non-Recyclable / Residual Waste'), ('ewaste', 'E-Waste'), ('hazardous', 'Hazardous Waste'), ('construction', 'Construction & Demolition Waste')], max_length=20),
        ),
    ]
