# Generated by Django 5.1.6 on 2025-09-04 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotracksys', '0003_alter_pickuprequest_options_pickuprequest_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collector_issues', to=settings.AUTH_USER_MODEL)),
                ('pickup_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='ecotracksys.pickuprequest')),
            ],
        ),
    ]
