# Generated by Django 5.1.6 on 2025-09-04 15:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotracksys', '0004_issue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-applied_at']},
        ),
        migrations.RenameField(
            model_name='leaverequest',
            old_name='end_date',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='leaverequest',
            old_name='start_date',
            new_name='to_date',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='created_at',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='applied_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='collector',
            field=models.ForeignKey(help_text='Collector who applied for leave', limit_choices_to={'role': 'collector'}, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('Sick', 'Sick'), ('Casual', 'Casual'), ('Annual', 'Annual')], max_length=20),
        ),
    ]
