# Generated by Django 5.1.6 on 2025-09-04 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecotracksys', '0005_alter_leaverequest_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='from_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='leaverequest',
            old_name='to_date',
            new_name='start_date',
        ),
    ]
