# Generated by Django 5.1.6 on 2025-09-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotracksys', '0008_collectorshift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuprequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In-Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Missed', 'Missed')], default='Pending', max_length=20),
        ),
    ]
