# Generated by Django 5.1.6 on 2025-09-11 07:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotracksys', '0009_alter_pickuprequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorshift',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='collectorshift',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
