# Generated by Django 5.1.6 on 2025-09-11 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotracksys', '0010_collectorshift_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='assigned_collector',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'collector'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pickups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
